server:
  port: 7001
eureka:
  instance:
    hostname: localhost # eureka服务端的实例名称
  client:
    register-with-eureka: false # 不向注册中心注册自己
    fetch-registry: false # 是否在本地缓存注册表信息,不需要去检索服务，我自己就是服务注册中心。负责维护服务的实例
    eureka-server-u-r-l-context:

