spring:
  application:
    name: micro-dept # 对外暴露的微服务名称
  datasource:
    url: jdbc:mysql://localhost:3306/java_123456?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: 123456
    driver-class-name: com.alibaba.druid.proxy.DruidDriver